# Generated by Django 3.2.8 on 2022-01-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='holla',
        ),
    ]
